CREATE TABLE TB_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME VARCHAR2(20) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	STD_GENDER CHAR(1) CHECK(STD_GENDER IN('M', 'F')),
	STD_SCORE CHAR(1) CHECK(STD_SCORE IN('A', 'B', 'C', 'D', 'F'))
);

CREATE SEQUENCE STD_NO_SEQ
START WITH 104
NOCACHE
;

INSERT INTO TB_STUDENT 
VALUES(101, '홍길동', '20', 'M', 'A'); 

INSERT INTO TB_STUDENT 
VALUES(102, '김철수', '21', 'M', 'A'); 

INSERT INTO TB_STUDENT 
VALUES(103, '이미림', '22', 'F', 'B'); 

SELECT * FROM TB_STUDENT;

SELECT STD_NO,
			STD_NAME,
			STD_AGE,
			STD_GENDER,
			STD_SCORE
		FROM TB_STUDENT
		;
		
COMMIT;
